site_name: Neptune

theme: cinder
repo_url: "https://github.com/phac-nml/neptune"
site_favicon: neptune.ico
copyright: "Neptune is licensed under the <a href='https://github.com/phac-nml/neptune/blob/release/1.2/LICENSE.txt'>Apache License Version 2.0</a><br>Copyright Government of Canada 2015-2017"

pages:
    - Home: index.md
    - News:
        - news.md
        - CHANGELOG.md
    - Install:
        - Neptune: install.md
    - Parameters: parameters.md
    - Examples:
        - Simple: examples.md
        - Walkthrough: walkthrough.md
    - Output:
        - Neptune: output.md
        - Signature Format: format.md
