site_name: Neptune

theme: readthedocs
repo_url: "https://github.com/phac-nml/neptune"
copyright: "Neptune is licensed under the <a href='https://github.com/phac-nml/neptune/blob/release/1.2/LICENSE.txt'>Apache License Version 2.0</a><br>Copyright Government of Canada 2015-2024"

nav:
    - Home: index.md
    - News:
        - news.md
        - CHANGELOG.md
    - Install:
        - Neptune: install.md
    - Parameters: parameters.md
    - Examples:
        - Simple: examples.md
        - Walkthrough: walkthrough.md
    - Output:
        - Neptune: output.md
        - Signature Format: format.md
